export const pluginName = "Hierarchy Tool"
export const githubReadmeUrl = "https://github.com/YU000jp/logseq-plugin-hierarchy-tool"
export const icon = "🪧"
export const keyToolbar = "twsToolbar"
export const keyToolbarPopup = keyToolbar + "Popup"
export const keyToolbarPopupFull = `logseq-plugin-hierarchy-tool--${keyToolbarPopup}`
export const keyToolbarSelectPage = keyToolbar + "SelectPage"
export const keyToolbarIncrementalContainer = keyToolbar + "IncrementalContainer"
export const keyToolbarIncrementalSearchBox = keyToolbar + "IncrementalSearchBox"
export const keyToolbarIncrementalSearchResult = keyToolbar + "IncrementalSearchResult"
export const keyToolbarHeaderSpace = keyToolbar + "HeaderSpace"
export const keyToolbarHierarchy = keyToolbar + "Hierarchy"
export const keyToolbarHierarchyContainer = keyToolbar + "HierarchyContainer"
export const keyToolbarTocContainer = keyToolbar + "TocContainer"
export const keyToolbarTocContent = keyToolbar + "TocContent"
export const headerCellClassSubPage = keyToolbar + "SubPage"
export const headerCellClassPageContent = keyToolbar + "PageContent"
export const keyToggleTableId = "tws--toggleHeader"
export const keyCreateSubPageButton = "twsCreateSubPageButton"
export const keySettingsButton = "twsSettingsButton"
export const twsToggle = "twsToggle"
export const keyToggleSubPage = `${twsToggle}SubPage`
export const keyToggleH1 = `${twsToggle}H1`
export const keyToggleH2 = `${twsToggle}H2`
export const keyToggleH3 = `${twsToggle}H3`
export const keyToggleH4 = `${twsToggle}H4`
export const keyToggleH5 = `${twsToggle}H5`
export const keyToggleH6 = `${twsToggle}H6`
export const keyRefreshButton = "twsRefreshButton"
export const keyToggleStyleForHideBlock = "twsToggleStyleForHideBlock"
export const keyCssHideHierarchyInPageContent = "twsHideHierarchyInPageContent"
export const keyCssHidePageTagsInPageContent = "twsHidePageTagsInPageContent"
export const keyCssClassHierarchyGroup = "tws--hierarchy-group"
export const keyCssClassHierarchyItem = "tws--hierarchy-item"
export const keyDialogCreateSubPageSearchResult = "incrementalSearchResult"
export const keyCommand = "hierarchyToolPopupTrigger"