export const pluginName = "Hierarchy Tool"
export const githubReadmeUrl = "https://github.com/YU000jp/logseq-plugin-hierarchy-tool"
export const icon = "🛢️"
export const keyToolbar = "hierarchyTool"
export const keyToolbarPopup = keyToolbar + "Popup"
export const keyToolbarPopupFull = `logseq-plugin-hierarchy-tool--${keyToolbarPopup}`
export const keyToolbarSelectPage = keyToolbar + "SelectPage"
export const keyToolbarIncrementalContainer = keyToolbar + "IncrementalContainer"
export const keyToolbarIncrementalSearchBox = keyToolbar + "IncrementalSearchBox"
export const keyToolbarIncrementalSearchResult = keyToolbar + "IncrementalSearchResult"
export const keyToolbarHeaderSpace = keyToolbar + "HeaderSpace"
export const keyToolbarHierarchy = keyToolbar + "Hierarchy"
export const keyToolbarHierarchyContainer = keyToolbar + "HierarchyContainer"
export const keyToolbarTocContainer = keyToolbar + "TocContainer"
export const keyToolbarTocContent = keyToolbar + "TocContent"
export const headerCellClassSubPage = keyToolbar + "SubPage"
export const headerCellClassPageContent = keyToolbar + "PageContent"
export const keyToggleTableId = "ht--toggleHeader"
export const keyCreateSubPageButton = "htCreateSubPageButton"
export const keySettingsButton = "htSettingsButton"
export const htToggle = "htToggle"
export const keyToggleSubPage = `${htToggle}SubPage`
export const keyToggleH1 = `${htToggle}H1`
export const keyToggleH2 = `${htToggle}H2`
export const keyToggleH3 = `${htToggle}H3`
export const keyToggleH4 = `${htToggle}H4`
export const keyToggleH5 = `${htToggle}H5`
export const keyToggleH6 = `${htToggle}H6`
export const keyRefreshButton = "htRefreshButton"
export const keyToggleStyleForHideBlock = "htToggleStyleForHideBlock"
export const keyCssHideHierarchyInPageContent = "htHideHierarchyInPageContent"
export const keyCssHidePageTagsInPageContent = "htHidePageTagsInPageContent"
export const keyCssClassHierarchyGroup = "ht--hierarchy-group"
export const keyCssClassHierarchyItem = "ht--hierarchy-item"
export const keyDialogCreateSubPageSearchResult = "incrementalSearchResult"
export const keyCommand = "hierarchyToolPopupTrigger"